### PR TITLE
add: docker for deployment

### PR DESCRIPTION
**Pull request by kymppi**

### CODE REVIEW

**Review by washbin — COMMENTED** [review]
Looks good to me, but how is the redis handled in docker ?
oh and may be we could add another workflow to create a binary and release it along with the docker image, just in case : )

**Comment by kymppi** [comment]
> Looks good to me, but how is the redis handled in docker ? oh and may be we could add another workflow to create a binary and release it along with the docker image, just in case : )

The redis would be it's own container, I can add a docker-compose.yml for easily starting the bot and redis. We don't need to include redis, since its already in [docker hub](https://hub.docker.com/_/redis)

**Comment by washbin** [comment]
> > Looks good to me, but how is the redis handled in docker ? oh and may be we could add another workflow to create a binary and release it along with the docker image, just in case : )
> 
> The redis would be it's own container, I can add a docker-compose.yml for easily starting the bot and redis. We don't need to include redis, since its already in [docker hub](https://hub.docker.com/_/redis)

Yeah that would be great. let's merge after docker-compose then

**Review by washbin — APPROVED** [review]
Looks good to me!

**Pull request merged**
